/**
 * RoboParts URDF Download API
 * GET /api/urdf/download?id=URDF-001
 *
 * Returns actual URDF XML content for download.
 * For preset models, generates valid URDF based on model metadata.
 * For branded models, provides redirect to official source or generated skeleton.
 */

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Content-Type': 'application/xml; charset=utf-8',
};

export async function onRequestOptions() {
  return new Response(null, { headers: corsHeaders });
}

export async function onRequestGet(context) {
  const { request, env } = context;
  const url = new URL(request.url);
  const id = url.searchParams.get('id');

  if (!id) {
    return new Response(JSON.stringify({
      error: 'Missing id parameter',
      message: '请提供 id 参数，例如: /api/urdf/download?id=URDF-001',
      hint: '访问 /api/urdf/library 获取可用模型列表',
    }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=utf-8' },
    });
  }

  // Load models from KV or preset
  const models = await loadModels(env);
  const model = models.find(m => m.id === id);

  if (!model) {
    return new Response(JSON.stringify({
      error: 'Model not found',
      message: '未找到 ID 为 ' + id + ' 的 URDF 模型',
      available_ids: models.slice(0, 10).map(m => m.id),
      total_available: models.length,
    }), {
      status: 404,
      headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=utf-8' },
    });
  }

  // Generate URDF XML content
  const urdfContent = generateURDF(model);

  // Use ASCII-safe filename with model ID, plus UTF-8 filename for modern browsers
  const safeFilename = (model.id || 'model') + '.urdf';
  const utf8Filename = encodeURIComponent((model.name || model.id) + '.urdf');

  return new Response(urdfContent, {
    status: 200,
    headers: {
      ...corsHeaders,
      'Content-Disposition': `attachment; filename="${safeFilename}"; filename*=UTF-8''${utf8Filename}`,
      'Cache-Control': 'public, max-age=3600',
    },
  });
}

// Generate valid URDF XML from model metadata
function generateURDF(model) {
  const joints = model.joints || 6;
  const links = model.links || joints + 1;
  const robotName = (model.name || model.id).replace(/[<>&"']/g, '');

  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += `<!-- RoboParts URDF Model: ${robotName} (${model.id}) -->\n`;
  xml += `<!-- Type: ${model.robot_type} | Joints: ${joints} | Payload: ${model.payload || 'N/A'} -->\n`;
  xml += `<!-- License: ${model.license || 'MIT'} | Author: ${model.author || 'RoboParts'} -->\n`;
  xml += `<!-- Generated by RoboParts.cc URDF Library -->\n`;
  xml += `<robot name="${robotName.replace(/\s+/g, '_')}">\n\n`;

  // Base link
  xml += `  <!-- Base Link -->\n`;
  xml += `  <link name="base_link">\n`;
  xml += `    <visual>\n`;
  xml += `      <origin xyz="0 0 0" rpy="0 0 0"/>\n`;
  xml += `      <geometry>\n`;
  xml += `        <box size="0.1 0.1 0.05"/>\n`;
  xml += `      </geometry>\n`;
  xml += `    </visual>\n`;
  xml += `    <collision>\n`;
  xml += `      <geometry><box size="0.1 0.1 0.05"/></geometry>\n`;
  xml += `    </collision>\n`;
  xml += `    <inertial>\n`;
  xml += `      <mass value="1.0"/>\n`;
  xml += `      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>\n`;
  xml += `    </inertial>\n`;
  xml += `  </link>\n\n`;

  // Generate joints and links based on type
  const jointConfigs = getJointConfigs(model.robot_type, joints);

  for (let i = 0; i < jointConfigs.length; i++) {
    const jc = jointConfigs[i];
    const parentName = i === 0 ? 'base_link' : `link_${i}`;
    const childName = `link_${i + 1}`;

    xml += `  <!-- Joint ${i + 1}: ${jc.name} -->\n`;
    xml += `  <joint name="joint_${i + 1}" type="${jc.type}">\n`;
    xml += `    <parent link="${parentName}"/>\n`;
    xml += `    <child link="${childName}"/>\n`;
    xml += `    <origin xyz="${jc.xyz}" rpy="${jc.rpy || '0 0 0'}"/>\n`;
    xml += `    <axis xyz="${jc.axis}"/>\n`;
    xml += `    <limit lower="${jc.lower || -3.14}" upper="${jc.upper || 3.14}" effort="${jc.effort || 100}" velocity="${jc.velocity || 1.0}"/>\n`;
    xml += `  </joint>\n\n`;

    xml += `  <link name="${childName}">\n`;
    xml += `    <visual>\n`;
    xml += `      <origin xyz="0 0 ${jc.length / 2}" rpy="0 0 0"/>\n`;
    xml += `      <geometry>\n`;
    xml += `        <cylinder radius="0.03" length="${jc.length}"/>\n`;
    xml += `      </geometry>\n`;
    xml += `    </visual>\n`;
    xml += `    <collision>\n`;
    xml += `      <geometry><cylinder radius="0.03" length="${jc.length}"/></geometry>\n`;
    xml += `    </collision>\n`;
    xml += `    <inertial>\n`;
    xml += `      <mass value="0.5"/>\n`;
    xml += `      <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>\n`;
    xml += `    </inertial>\n`;
    xml += `  </link>\n\n`;
  }

  // Add material
  xml += `  <material name="roboparts_blue">\n`;
  xml += `    <color rgba="0.02 0.71 0.83 1.0"/>\n`;
  xml += `  </material>\n\n`;

  xml += `</robot>\n`;

  return xml;
}

// Generate joint configurations based on robot type
function getJointConfigs(robotType, totalJoints) {
  const configs = [];
  const count = Math.min(totalJoints, 28);

  if (robotType === 'humanoid') {
    // Simplified humanoid: split between arms and legs
    const perArm = Math.floor((count - 2) / 4); // 2 legs + 2 arms
    // Left leg
    for (let i = 0; i < perArm; i++) {
      configs.push({
        name: `left_leg_${i + 1}`,
        type: i === 0 ? 'revolute' : 'revolute',
        xyz: i === 0 ? '0.05 0 -0.05' : `0 0 -${0.15 + i * 0.05}`,
        axis: i === 0 ? '0 1 0' : '0 1 0',
        length: 0.15,
        effort: 200, velocity: 2.0,
      });
    }
    // Right leg
    for (let i = 0; i < perArm; i++) {
      configs.push({
        name: `right_leg_${i + 1}`,
        type: 'revolute',
        xyz: i === 0 ? '-0.05 0 -0.05' : `0 0 -${0.15 + i * 0.05}`,
        axis: '0 1 0',
        length: 0.15,
        effort: 200, velocity: 2.0,
      });
    }
    // Left arm
    for (let i = 0; i < perArm; i++) {
      configs.push({
        name: `left_arm_${i + 1}`,
        type: 'revolute',
        xyz: i === 0 ? '0.05 0 0.2' : `0 0 ${0.1 + i * 0.05}`,
        axis: i === 0 ? '1 0 0' : '0 1 0',
        length: 0.1,
        effort: 50, velocity: 3.0,
      });
    }
    // Right arm
    for (let i = 0; i < perArm; i++) {
      configs.push({
        name: `right_arm_${i + 1}`,
        type: 'revolute',
        xyz: i === 0 ? '-0.05 0 0.2' : `0 0 ${0.1 + i * 0.05}`,
        axis: i === 0 ? '1 0 0' : '0 1 0',
        length: 0.1,
        effort: 50, velocity: 3.0,
      });
    }
  } else if (robotType === 'quadruped') {
    // 4 legs, 3 joints each = 12
    const perLeg = Math.floor(count / 4);
    const legOffsets = [
      [0.1, 0.1], [-0.1, 0.1], [0.1, -0.1], [-0.1, -0.1]
    ];
    for (let leg = 0; leg < 4 && leg * perLeg < count; leg++) {
      for (let i = 0; i < perLeg; i++) {
        configs.push({
          name: `leg${leg + 1}_joint_${i + 1}`,
          type: 'revolute',
          xyz: i === 0 ? `${legOffsets[leg][0]} ${legOffsets[leg][1]} 0` : `0 0 -${0.1 + i * 0.08}`,
          axis: i === 0 ? '1 0 0' : '0 1 0',
          length: 0.1,
          effort: 100, velocity: 2.0,
        });
      }
    }
  } else if (robotType === 'arm') {
    // Serial chain arm
    for (let i = 0; i < count; i++) {
      configs.push({
        name: `joint_${i + 1}`,
        type: i === 0 ? 'revolute' : 'revolute',
        xyz: i === 0 ? '0 0 0.05' : `0 0 ${0.1 + i * 0.05}`,
        axis: i % 2 === 0 ? '0 1 0' : '1 0 0',
        length: 0.1,
        effort: 50, velocity: 2.0,
      });
    }
  } else if (robotType === 'hand' || robotType === 'gripper') {
    // Simple gripper
    const fingers = Math.min(count, 5);
    for (let i = 0; i < fingers; i++) {
      const side = i < fingers / 2 ? 1 : -1;
      configs.push({
        name: `finger_${i + 1}`,
        type: 'revolute',
        xyz: `${side * 0.02} 0 0.05`,
        axis: '1 0 0',
        length: 0.05,
        effort: 10, velocity: 5.0,
        lower: 0, upper: 1.5,
      });
    }
  } else {
    // Default: AMR or unknown - simple chain
    for (let i = 0; i < count; i++) {
      configs.push({
        name: `joint_${i + 1}`,
        type: i < 2 ? 'continuous' : 'fixed',
        xyz: i === 0 ? '0.1 0 0' : i === 1 ? '-0.1 0 0' : '0 0 0.1',
        axis: i < 2 ? '0 0 1' : '0 0 0',
        length: 0.1,
        effort: 100, velocity: 5.0,
      });
    }
  }

  return configs;
}

// Load models from KV or fallback to minimal preset
async function loadModels(env) {
  if (env.URDF_LIBRARY) {
    try {
      const raw = await env.URDF_LIBRARY.get('urdf_models');
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed;
        }
      }
    } catch (e) {
      // fall through to preset
    }
  }

  // Minimal fallback - return basic presets
  return [
    { id: 'URDF-001', name: '6-DOF机械臂基础模型', robot_type: 'arm', joints: 6, links: 7, license: 'MIT', author: 'RoboParts' },
    { id: 'URDF-002', name: '人形机器人上半身', robot_type: 'humanoid', joints: 14, links: 15, license: 'MIT', author: 'RoboParts' },
    { id: 'URDF-003', name: '四足机器人基础模型', robot_type: 'quadruped', joints: 12, links: 13, license: 'MIT', author: 'RoboParts' },
    { id: 'URDF-004', name: '机器人夹爪', robot_type: 'hand', joints: 2, links: 3, license: 'MIT', author: 'RoboParts' },
    { id: 'URDF-005', name: '人形机器人全身模型', robot_type: 'humanoid', joints: 28, links: 29, license: 'Apache-2.0', author: 'RoboParts' },
  ];
}

// HEAD 探活：Pages 不把 HEAD 映射到 onRequestGet，缺此导出则一律 404 ——
// 对外声明过的地址被目录站/监控探成"不存在"。完整复盘见 functions/mcp.js 同名函数。
export async function onRequestHead(context) {
  const r = await onRequestGet(context);
  return new Response(null, { status: r.status, headers: r.headers });
}
